@startuml Blockchain
    package "Blockchain" {
        class Blockchain {
            - ImmutableList<Block> Chain
            + Task AddBlockAsync(Block block)
            + Task<Block> GetLastBlockAsync()
            + Task<string?> GetLastBlockHashAsync()
            + Task<int> GetLastIndexAsync()
            + Task LoadBlocksFromBd()
        }
        
        class Block {
            - string Id
            - int Index
            - DateTime Timestamp
            - List<Transaction> Transactions
            - string MerkleRoot
            - string PreviousHash
            - string Hash
            - int Difficulty
            - string Nonce
            - string Signature 
            - int Size
            + string GenerateHash()
            + int CalculateSize()
            + BlockModel ToBlockModel()
            + Block FromBlockModel(BlockModel model)
            + string ToString()
          
        }
        
        class BlockBuilder {
            - TransactionMemoryPool _transactionMemoryPool
            - const int MaxWaitTimeInSeconds = 30000
            - DateTime lastTransactionTime
            - const int MaxTransactionLimit = 1
            - Blockchain _blockChain
            - MerkleTree _merkleTree
            - BlockManager _blockManager
            - IDbProcessor _dbProcessor
            - int CurrentDifficulty { get; set; } = 2
            + Task<Block> StartBuilding()
            + Task<bool> TryBuildBlock()
            + Task<Block> BuildBlockAsync()
            + string MineBlock(Block block)
            + string GenerateNonce()
            + string SignBlock(Block block)
            + Task<Block> CreateGenesisBlock()
            + int GetCurrentDifficulty(int blockIndex)
        }
        
        class BlockManager {
            - RSA _privateKey
            + string SignBlock(string generateHash)
            + List<TransactionModel> GetTransactionsFromBlock(BlockModel block)
        }
        
        class Transaction {
            - string Id
            - string BlockId
            - string Sender
            - string Receiver
            - decimal Amount
            - DateTime Timestamp
            - decimal Fee 
            - string Signature
            - Object? Data
            - SmartContract? Contract 
            - string PublicKey
            + string ToString()
            + int CalculateSize()
            + TransactionModel ToModel(Transaction transaction)
            + Transaction ToEntity(TransactionModel model)
            + string Serialize(Transaction model)
        }
        
        class MerkleRoot {
            + string CalculateMerkleRoot(List<Transaction> transactions)
            + string BuildTree(List<string> nodes)
            + string CalculateHash(string input)
            + string SerializeTransaction(Transaction tx)
        }
        
        class TransactionMemoryPool {
            - HashSet<string> transactionSet
            - PriorityQueue<Transaction, decimal> priorityQueue
            + bool AddTransaction(Transaction transaction)
            + Transaction GetHighestFeeTransaction()
            + bool ContainsTransaction(string transactionId)
            + int GetTransactionCount()
            + void FillFromRedis(RedisService redisService)
            + Task FillFromSqlLite()
        }
        
        BlockBuilder -> Blockchain : Uses
        Blockchain -> Block : Uses
        BlockBuilder -> Block : Uses
        BlockBuilder -> BlockManager : Uses
        BlockBuilder -> Transaction
        BlockBuilder -> MerkleRoot
        BlockBuilder -> TransactionMemoryPool
        
        TransactionMemoryPool -> Transaction
    }
@enduml